services:
  db:
    image: postgres:17
    container_name: db-container
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_PROD_DBNAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USERNAME}", "-d", "${POSTGRES_PROD_DBNAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
    
  api:
    image: api-tutorial
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-container
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    ports:
      - "8080:8080"
    # restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]

volumes:
  pg_data: